prefix : <https://purl.org/prozion/semtech#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix afn: <http://jena.apache.org/ARQ/function#>

select ?person_name ?place where {
  # ?s :author ?person .
  ?s ?p_maker ?person .
  ?s rdf:type :Specification .
  ?p_maker rdfs:subPropertyOf* :maker .
  {
    ?person ?p_place ?place .
    ?p_place rdfs:subPropertyOf* :place .
  }
  union
  {
    ?person ?p2 ?company .
    ?p2 rdfs:subPropertyOf* :stuff .
    ?company :hq ?place .
  }
  ?place :country :UK .
  bind (replace(str(afn:localname(?person)), "_", " ") as ?person_name)
}
